import type {
  AuditFinding,
  AuditReport,
  PageMetrics,
  TrendDelta,
  WeeklyTrend,
} from "../types";

/**
 * Generate a markdown audit report with 5 sections:
 *
 * 1. Summary — key metrics at a glance with trend arrows
 * 2. Performance — per-page Lighthouse scores (mobile + desktop)
 * 3. Behavioral — PostHog metrics (rage clicks, dead clicks, etc.)
 * 4. Findings — prioritized issues with recommendations
 * 5. Actions — next steps checklist
 */
export function generateMarkdownReport(
  report: AuditReport,
  findings: AuditFinding[],
  trends: WeeklyTrend,
): string {
  const lines: string[] = [];

  lines.push(`# 📊 Weekly UX Audit Report`);
  lines.push(``);
  lines.push(`**Generated:** ${formatDate(report.generatedAt)}`);
  lines.push(`**Site:** https://ayasser.com`);
  lines.push(`**Pages analyzed:** ${report.pages.length}`);
  lines.push(``);

  // Section 1: Summary
  lines.push(`## 📋 Summary`);
  lines.push(``);
  lines.push(buildSummaryTable(report, trends));
  lines.push(``);

  // Section 2: Performance
  lines.push(`## 🚀 Performance (Lighthouse Lab Data)`);
  lines.push(``);
  lines.push(buildPerformanceTable(report.pages));
  lines.push(``);

  // CrUX field data note
  const hasFieldData = report.pages.some(
    (p) => p.psiMobile?.field.available || p.psiDesktop?.field.available,
  );
  if (!hasFieldData) {
    lines.push(
      `> **Note:** CrUX field data is not available for this site (insufficient traffic for Chrome's dataset). Lab data from Lighthouse is shown instead.`,
    );
    lines.push(``);
  }

  // Section 3: Behavioral
  lines.push(`## 🔍 Behavioral (PostHog)`);
  lines.push(``);
  if (report.behavioral) {
    lines.push(buildBehavioralTable(report));
    lines.push(``);

    if (report.behavioral.topPages.length > 0) {
      lines.push(`### Top Pages by Sessions`);
      lines.push(``);
      lines.push(`| Page | Sessions | Page Views |`);
      lines.push(`|------|----------|------------|`);
      for (const page of report.behavioral.topPages.slice(0, 10)) {
        lines.push(`| ${page.title} | ${page.sessions} | ${page.pageViews} |`);
      }
      lines.push(``);
    }
  } else {
    lines.push(`_PostHog data not available for this run._`);
    lines.push(``);
  }

  // Section 4: Findings
  lines.push(`## ⚠️ Findings`);
  lines.push(``);
  if (findings.length === 0) {
    lines.push(`✅ **All green!** No threshold breaches detected.`);
  } else {
    lines.push(`Found **${findings.length}** issue(s):`);
    lines.push(``);

    const critical = findings.filter((f) => f.severity === "critical");
    const warnings = findings.filter((f) => f.severity === "warning");
    const info = findings.filter((f) => f.severity === "info");

    if (critical.length > 0) {
      lines.push(`### 🔴 Critical (${critical.length})`);
      lines.push(``);
      for (const f of critical) {
        lines.push(formatFinding(f));
      }
      lines.push(``);
    }

    if (warnings.length > 0) {
      lines.push(`### 🟡 Warning (${warnings.length})`);
      lines.push(``);
      for (const f of warnings) {
        lines.push(formatFinding(f));
      }
      lines.push(``);
    }

    if (info.length > 0) {
      lines.push(`### 🔵 Info (${info.length})`);
      lines.push(``);
      for (const f of info) {
        lines.push(formatFinding(f));
      }
      lines.push(``);
    }
  }

  // Section 5: Actions
  lines.push(`## 📝 Recommended Actions`);
  lines.push(``);
  lines.push(buildActionChecklist(findings));
  lines.push(``);

  // Errors
  if (report.errors.length > 0) {
    lines.push(`---`);
    lines.push(``);
    lines.push(`## Errors During Collection`);
    lines.push(``);
    for (const err of report.errors) {
      lines.push(`- **[${err.source}]** ${err.message} _(${err.timestamp})_`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`_Report generated by `);
  lines.push(
    `[\`npm run audit\`](https://github.com/ayasserm/personal-website/tree/main/scripts/audit)_`,
  );

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function buildSummaryTable(report: AuditReport, trends: WeeklyTrend): string {
  const lines: string[] = [];

  lines.push(`| Metric | Value | Trend |`);
  lines.push(`|--------|-------|-------|`);

  // Avg mobile perf score
  if (trends.performanceScore) {
    lines.push(
      `| Avg Mobile Perf Score | ${Math.round(trends.performanceScore.current * 100)}/100 | ${trendArrow(trends.performanceScore)} |`,
    );
  }

  // Avg LCP
  if (trends.lcp) {
    lines.push(
      `| Avg Mobile LCP | ${(trends.lcp.current / 1000).toFixed(1)}s | ${trendArrow(trends.lcp)} |`,
    );
  }

  // Avg TBT
  if (trends.tbt) {
    lines.push(
      `| Avg Mobile TBT | ${Math.round(trends.tbt.current)}ms | ${trendArrow(trends.tbt)} |`,
    );
  }

  // PostHog behavioral
  if (trends.totalSessions) {
    lines.push(
      `| Total Sessions | ${Math.round(trends.totalSessions.current)} | ${trendArrow(trends.totalSessions)} |`,
    );
  }
  if (trends.rageClicks) {
    lines.push(
      `| Rage Clicks | ${Math.round(trends.rageClicks.current)} | ${trendArrow(trends.rageClicks)} |`,
    );
  }
  if (trends.deadClicks) {
    lines.push(
      `| Dead Clicks | ${Math.round(trends.deadClicks.current)} | ${trendArrow(trends.deadClicks)} |`,
    );
  }

  if (report.behavioral) {
    const sd = report.behavioral.averageScrollDepth;
    lines.push(
      `| Avg Scroll Depth | ${sd !== null ? `${Math.round(sd)}%` : "N/A"} | — |`,
    );
  }

  return lines.join("\n");
}

function buildPerformanceTable(pages: readonly PageMetrics[]): string {
  const lines: string[] = [];

  lines.push(
    `| Page | Mobile Score | Desktop Score | Mobile LCP | Mobile FCP | Mobile TBT | Mobile CLS |`,
  );
  lines.push(
    `|------|:-----------:|:------------:|:----------:|:----------:|:----------:|:----------:|`,
  );

  for (const page of pages) {
    const m = page.psiMobile?.lab;
    const d = page.psiDesktop?.lab;

    const mScore = m ? scoreEmoji(m.performanceScore) : "—";
    const dScore = d ? scoreEmoji(d.performanceScore) : "—";
    const mLcp = m ? `${(m.lcp / 1000).toFixed(1)}s` : "—";
    const mFcp = m ? `${(m.fcp / 1000).toFixed(1)}s` : "—";
    const mTbt = m ? `${Math.round(m.tbt)}ms` : "—";
    const mCls = m ? m.cls.toFixed(3) : "—";

    lines.push(
      `| ${page.name} | ${mScore} | ${dScore} | ${mLcp} | ${mFcp} | ${mTbt} | ${mCls} |`,
    );
  }

  return lines.join("\n");
}

function buildBehavioralTable(report: AuditReport): string {
  const c = report.behavioral;
  if (!c) return "_No PostHog data._";

  const lines: string[] = [];
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Sessions | ${c.totalSessions} |`);
  lines.push(`| Distinct Users | ${c.distinctUsers} |`);
  lines.push(`| Bot Sessions | ${c.botSessions} |`);
  lines.push(`| Pages/Session | ${c.pagesPerSession ?? "N/A"} |`);
  lines.push(`| Rage Clicks | ${c.rageClicks} |`);
  lines.push(`| Dead Clicks | ${c.deadClicks} |`);
  lines.push(`| Excessive Scrolls | ${c.excessiveScrolls} |`);
  lines.push(`| Quickback Clicks | ${c.quickbackClicks} |`);
  lines.push(`| Script Errors | ${c.scriptErrors} |`);
  lines.push(
    `| Avg Scroll Depth | ${c.averageScrollDepth !== null ? `${Math.round(c.averageScrollDepth)}%` : "N/A"} |`,
  );

  const engTotal =
    c.totalEngagementTime !== null
      ? formatDuration(c.totalEngagementTime)
      : "N/A";
  const engActive =
    c.activeEngagementTime !== null
      ? formatDuration(c.activeEngagementTime)
      : "N/A";
  lines.push(`| Total Engagement | ${engTotal} |`);
  lines.push(`| Active Engagement | ${engActive} |`);

  return lines.join("\n");
}

function buildActionChecklist(findings: AuditFinding[]): string {
  if (findings.length === 0) {
    return "- [x] All metrics within thresholds — no action needed this week";
  }

  // Deduplicate recommendations (same rec can appear for multiple pages)
  const seen = new Set<string>();
  const actions: string[] = [];

  for (const f of findings) {
    if (f.severity === "info") continue; // Only actionable items
    if (seen.has(f.recommendation)) continue;
    seen.add(f.recommendation);
    actions.push(`- [ ] ${f.recommendation}`);
  }

  // Add info items as lower priority
  for (const f of findings) {
    if (f.severity !== "info") continue;
    if (seen.has(f.recommendation)) continue;
    seen.add(f.recommendation);
    actions.push(`- [ ] _(Low priority)_ ${f.recommendation}`);
  }

  return actions.join("\n");
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function trendArrow(delta: TrendDelta): string {
  if (delta.delta === null) return "_(first run)_";
  if (delta.direction === "up") return "↑ improved";
  if (delta.direction === "down") return "↓ regressed";
  return "→ flat";
}

function scoreEmoji(score: number): string {
  const pct = Math.round(score * 100);
  if (pct >= 90) return `🟢 ${pct}`;
  if (pct >= 70) return `🟡 ${pct}`;
  return `🔴 ${pct}`;
}

function formatFinding(f: AuditFinding): string {
  const pageLabel = f.page ? ` — **${f.page}**` : "";
  return `- **${f.metric}**${pageLabel}: ${f.message}\n  > 💡 ${f.recommendation}\n`;
}

function formatDuration(seconds: number): string {
  if (seconds < 60) return `${Math.round(seconds)}s`;
  const mins = Math.floor(seconds / 60);
  const secs = Math.round(seconds % 60);
  return `${mins}m ${secs}s`;
}
